from django.db import models

class Skill(models.Model):
    """
    Standardized tags for skills (e.g., 'Python', 'Public Speaking').
    Used for analytics and AI context.
    """
    name = models.CharField(max_length=100, unique=True)
    
    def save(self, *args, **kwargs):
        self.name = self.name.lower().strip() # Normalize to lowercase
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Certificate(models.Model):
    class Status(models.TextChoices):
        PENDING = 'PENDING', 'AI Processing'
        AI_VERIFIED = 'AI_VERIFIED', 'Verified by AI'
        NEEDS_REVIEW = 'NEEDS_REVIEW', 'Sent to Mentor'
        MANUAL_VERIFIED = 'MANUAL_VERIFIED', 'Verified by Mentor'
        REJECTED = 'REJECTED', 'Rejected'

    # Link to the Student
    student = models.ForeignKey(
        'users.Profile', 
        on_delete=models.CASCADE, 
        related_name='certificates'
    )
    
    # --- USER INPUTS ---
    title = models.CharField(max_length=255)
    issuing_organization = models.CharField(max_length=255)
    file_url = models.FileField(upload_to='certificates/')
    
    # Link Skills (User Claims): What the student SAYS they learned
    claimed_skills = models.ManyToManyField(
        Skill, 
        related_name='claimed_certificates',
        blank=True
    )

    # --- AI & VERIFICATION DATA ---
    
    # The "Smart" Description generated by LLM (used for Portfolio/Chatbot)
    generated_description = models.TextField(blank=True, null=True)
    
    # Raw text read from the image (Evidence)
    ocr_text = models.TextField(blank=True, null=True)
    
    # Validated Skills: The subset of claimed_skills that the AI/Mentor confirmed
    verified_skills = models.ManyToManyField(
        Skill, 
        related_name='verified_certificates',
        blank=True
    )

    # --- STATUS & SCORING ---
    status = models.CharField(
        max_length=20, 
        choices=Status.choices, 
        default=Status.PENDING
    )
    
    credit_points = models.IntegerField(default=0)
    
    # If verified manually by mentor
    verified_by = models.ForeignKey(
        'users.Profile', 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        related_name='reviewed_certificates'
    )
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} ({self.student.identifier})"