# Generated by Django 5.2.7 on 2025-12-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('board_or_university', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('10', 'Class 10'), ('12', 'Class 12'), ('DIPLOMA', 'Diploma'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=20)),
                ('score', models.CharField(help_text='e.g. 9.8 CGPA or 88%', max_length=20)),
                ('passing_year', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='profiles.studentprofile')),
            ],
            options={
                'ordering': ['-passing_year'],
            },
        ),
    ]
