# Generated by Django 5.2.7 on 2025-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_certificate_reason'),
        ('profiles', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='achievements.skill'),
        ),
    ]
