# Generated by Django 5.2.7 on 2025-12-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_phd_awarded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='phd_qualification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='publications_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='differently_abled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phd_enrolled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
