# Generated by Django 5.2.7 on 2026-03-03 15:42
# Fixed: column was manually deleted from DB, so we use
# SeparateDatabaseAndState to reconcile Django's state with the DB.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_studentprofile_skills"),
    ]

    operations = [
        # Step 1: Remove the old field from Django's state only (column already gone from DB)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="studentprofile",
                    name="batch_year",
                ),
            ],
            database_operations=[],  # Nothing to do in DB — column is already deleted
        ),
        # Step 2: Add the new DateField column (both in state and DB)
        migrations.AddField(
            model_name="studentprofile",
            name="batch_year",
            field=models.DateField(null=True),
        ),
    ]
