# Generated by Django 5.2.7 on 2025-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rollnumber',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
