# Generated by Django 5.2.7 on 2025-11-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_contact_institution_street'),
        ('users', '0002_profile_rollnumber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('rollnumber', 'institution', 'department')},
        ),
    ]
