# Generated by Django 5.2.7 on 2025-11-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_contact_institution_street'),
        ('users', '0003_alter_profile_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rollnumber',
            new_name='identifier',
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('identifier', 'institution', 'department')},
        ),
    ]
