# Generated by Django 5.2.7 on 2025-11-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_contact_institution_street'),
        ('users', '0004_rename_rollnumber_profile_identifier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('identifier', 'institution')},
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['FACULTY', 'HOD']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='users.profile'),
        ),
    ]
