# Generated by Django 5.2.7 on 2025-11-25 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_contact_institution_street'),
        ('users', '0005_alter_profile_unique_together_profile_mentor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('identifier__isnull', False), models.Q(('identifier', ''), _negated=True)), fields=('identifier', 'institution'), name='unique_identifier_per_institution'),
        ),
    ]
