# Generated by Django 5.2.7 on 2025-11-26 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_contact_institution_street'),
        ('users', '0008_remove_profile_unique_hod_per_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique_hod_per_institution',
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'HOD')), fields=('department', 'institution'), name='unique_hod_per_institution_department'),
        ),
    ]
