# Generated by Django 5.2.7 on 2025-11-24 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_profile_unique_together_profile_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('file_url', models.FileField(upload_to='certificates/')),
                ('generated_description', models.TextField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'AI Processing'), ('AI_VERIFIED', 'Verified by AI'), ('NEEDS_REVIEW', 'Sent to Mentor'), ('MANUAL_VERIFIED', 'Verified by Mentor'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('credit_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.profile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certificates', to='users.profile')),
                ('claimed_skills', models.ManyToManyField(blank=True, related_name='claimed_certificates', to='achievements.skill')),
                ('verified_skills', models.ManyToManyField(blank=True, related_name='verified_certificates', to='achievements.skill')),
            ],
        ),
    ]
