# Generated by Django 5.2.7 on 2025-12-01 19:05

import achievements.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('file_url', models.FileField(max_length=255, upload_to=achievements.models.certificate_upload_path)),
                ('verification_url', models.URLField(blank=True, help_text='Public URL to verify credentials (e.g. Coursera/Credly link)', null=True)),
                ('category', models.CharField(blank=True, choices=[('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('EXTENSION', 'Extension / Outreach (NSS/NCC)'), ('MOOC', 'MOOC / Online Course'), ('INTERNSHIP', 'Internship'), ('PROJECT', 'Project / Field Work'), ('TECHNICAL', 'Technical / Hackathon'), ('RESEARCH', 'Research Paper / Patent'), ('OTHER', 'Other')], max_length=50)),
                ('level', models.CharField(choices=[('COLLEGE', 'College / Inter-Collegiate'), ('STATE', 'State / University'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], default='COLLEGE', max_length=20)),
                ('rank', models.CharField(choices=[('PARTICIPATION', 'Participation'), ('FIRST', 'First Prize / Gold'), ('SECOND', 'Second Prize / Silver'), ('THIRD', 'Third Prize / Bronze'), ('WINNER', 'Winner')], default='PARTICIPATION', max_length=20)),
                ('date_of_event', models.DateField(help_text='Date mentioned on certificate')),
                ('academic_year', models.CharField(blank=True, help_text='Auto-generated (e.g. 2023-24)', max_length=10)),
                ('ai_summary', models.TextField(blank=True, help_text='Short summary for Chatbot context.')),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'AI Processing'), ('AI_VERIFIED', 'Verified by AI'), ('NEEDS_REVIEW', 'Sent to Mentor'), ('MANUAL_VERIFIED', 'Verified by Mentor'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('credit_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profiles.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_achievements', to='profiles.facultyprofile')),
                ('primary_skill', models.ForeignKey(help_text='The main skill this certificate validates.', on_delete=django.db.models.deletion.PROTECT, related_name='primary_achievements', to='achievements.skill')),
                ('secondary_skills', models.ManyToManyField(blank=True, related_name='secondary_achievements', to='achievements.skill')),
            ],
        ),
    ]
