# Generated by Django 5.2.7 on 2025-12-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_of_event',
            field=models.DateField(blank=True, help_text='Date mentioned on certificate'),
        ),
    ]
