# Generated by Django 5.2.7 on 2025-12-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_certificate_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_of_event',
            field=models.DateField(blank=True, help_text='Date mentioned on certificate', null=True),
        ),
    ]
