# Generated by Django 5.2.7 on 2025-12-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_certificate_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='primary_skill',
            field=models.ForeignKey(blank=True, help_text='The main skill this certificate validates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_achievements', to='achievements.skill'),
        ),
    ]
