# Generated by Django 5.2.7 on 2025-12-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_certificate_primary_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='primary_skill',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='secondary_skills',
        ),
    ]
