# Generated by Django 5.2.7 on 2025-12-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_certificate_primary_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='reason',
            field=models.TextField(blank=True, help_text='Verification reason or rejection cause.', null=True),
        ),
    ]
