# Generated by Django 5.2.7 on 2025-12-09 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_certificate_primary_skill_and_more'),
        ('profiles', '0003_education_is_phd_awarded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NirfExecDevelopment',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=255)),
                ('revenue_lakhs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('participants', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_development_programs', to='profiles.facultyprofile')),
            ],
            options={
                'db_table': 'nirf_exec_development',
            },
        ),
        migrations.CreateModel(
            name='NirfPatent',
            fields=[
                ('patent_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('patent_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('FILED', 'Filed'), ('PUBLISHED', 'Published'), ('GRANTED', 'Granted')], max_length=20)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('grant_date', models.DateField(blank=True, null=True)),
                ('inventor_position', models.CharField(blank=True, choices=[('FIRST', 'First'), ('CO_INVENTOR', 'Co-Inventor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nirf_patents', to='profiles.facultyprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nirf_patents', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'nirf_patents',
                'indexes': [models.Index(fields=['status', 'grant_date'], name='nirf_patent_status_9de3fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='NirfPublication',
            fields=[
                ('pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('journal_name', models.CharField(max_length=255)),
                ('scopus_wos_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('volume_issue', models.CharField(blank=True, max_length=50)),
                ('page_numbers', models.CharField(blank=True, max_length=50)),
                ('doi_url', models.URLField(blank=True, null=True)),
                ('pub_date', models.DateField()),
                ('citations', models.PositiveIntegerField(default=0)),
                ('author_position', models.CharField(blank=True, choices=[('FIRST', 'First'), ('CORRESPONDING', 'Corresponding'), ('CO_AUTHOR', 'Co-Author')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nirf_publications', to='profiles.facultyprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nirf_publications', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'nirf_publications',
                'indexes': [models.Index(fields=['pub_date', 'scopus_wos_id'], name='nirf_public_pub_dat_1be857_idx')],
            },
        ),
        migrations.CreateModel(
            name='NirfResearchProject',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('funding_agency', models.CharField(max_length=255)),
                ('amount_lakhs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_years', models.PositiveSmallIntegerField()),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('MAJOR', 'Major Project'), ('MINOR', 'Minor Project'), ('INDUSTRY', 'Industry Sponsored'), ('CONSULTANCY', 'Consultancy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pi_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nirf_projects', to='profiles.facultyprofile')),
            ],
            options={
                'db_table': 'nirf_research_projects',
                'indexes': [models.Index(fields=['start_year', 'funding_agency'], name='nirf_resear_start_y_8808fc_idx')],
            },
        ),
    ]
