# Generated by Django 5.2.7 on 2025-12-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_department_created_at_department_updated_at_and_more'),
        ('profiles', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniMaster',
            fields=[
                ('alumni_id', models.AutoField(primary_key=True, serialize=False)),
                ('graduation_year', models.IntegerField()),
                ('current_organization', models.CharField(blank=True, max_length=255)),
                ('current_designation', models.CharField(blank=True, max_length=255)),
                ('current_ctc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active_alumni', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_record', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'alumni_master',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('total_credits', models.PositiveIntegerField(default=160)),
                ('intake_capacity', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_courses', to='academics.department')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='PlacementRecords',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('ctc_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_letter_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SELECTED', 'Selected'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('JOINED', 'Joined'), ('REJECTED', 'Rejected')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_placements', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'placement_records',
                'ordering': ['-offer_letter_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('semester', models.PositiveSmallIntegerField()),
                ('credits', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('max_internal', models.PositiveIntegerField(default=25)),
                ('max_external', models.PositiveIntegerField(default=75)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='erp.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_subjects', to='academics.department')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['department__code', 'semester', 'subject_code'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_semester', models.PositiveSmallIntegerField()),
                ('batch_year', models.IntegerField()),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='profiles.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='erp.subject')),
            ],
            options={
                'db_table': 'student_subject_enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_code', models.CharField(max_length=20, unique=True)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('SUPPLEMENTARY', 'Supplementary')], max_length=20)),
                ('max_marks', models.PositiveIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('exam_date', models.DateField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='erp.subject')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='MarksGrades',
            fields=[
                ('marks_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='erp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_marks', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'marks_grades',
                'ordering': ['-entered_date'],
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='PlacementStats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_year', models.IntegerField()),
                ('total_students', models.PositiveIntegerField()),
                ('placed_students', models.PositiveIntegerField()),
                ('placement_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_ctc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('highest_ctc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_stats', to='academics.department')),
            ],
            options={
                'db_table': 'placement_stats',
                'unique_together': {('batch_year', 'department')},
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('course', 'department', 'subject_code', 'semester'), name='unique_subject_course_dept_sem'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectenrollment',
            unique_together={('student', 'subject', 'enrollment_semester')},
        ),
    ]
