# Generated by Django 5.2.7 on 2025-12-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnimaster',
            name='alumni_feedback_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='alumnimaster',
            name='higher_studies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='programme_type',
            field=models.CharField(blank=True, choices=[('UG', 'UG'), ('PG', 'PG'), ('PhD', 'PhD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sanctioned_intake',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marksgrades',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marksgrades',
            name='cgpa_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='placementrecords',
            name='median_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='placementrecords',
            name='programme_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
