# Generated by Django 5.2.7 on 2025-12-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alumnimaster_alumni_feedback_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NirfDiversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('count_ug', models.PositiveIntegerField()),
                ('count_pg', models.PositiveIntegerField()),
                ('count_phd', models.PositiveIntegerField()),
                ('academic_year', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'nirf_diversity',
            },
        ),
        migrations.CreateModel(
            name='NirfFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9, unique=True)),
                ('capital_expenditure_lakhs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_expenditure_lakhs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_students', models.PositiveIntegerField()),
                ('total_faculty', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'nirf_financials',
            },
        ),
        migrations.CreateModel(
            name='NirfPerception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nirf_year', models.IntegerField()),
                ('employer_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('academic_peer_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('survey_responses', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'nirf_perception',
            },
        ),
    ]
