# Generated by Django 5.2.7 on 2025-12-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_created_at_user_updated_at_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('RECRUITER', 'Recruiter')], default='STUDENT', max_length=50),
        ),
    ]
