# Generated by Django 5.2.7 on 2025-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty')], default='STUDENT', max_length=50),
        ),
    ]
