# Generated by Django 5.2.7 on 2025-12-05 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_department_created_at_department_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Map to your local department structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='academics.department')),
            ],
        ),
        migrations.CreateModel(
            name='LmsClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(default='active', max_length=20)),
                ('session_ids', models.JSONField(default=list)),
                ('enrollment_count', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(default='open', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('points_possible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grading_type', models.CharField(default='points', max_length=50)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lms.lmsclass')),
            ],
        ),
        migrations.CreateModel(
            name='LmsPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('roles', models.JSONField(default=list)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(db_index=True, max_length=20)),
                ('state', models.CharField(default='active', max_length=20)),
                ('final_letter_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('final_numeric_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.lmsclass')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.lmsperson')),
            ],
        ),
        migrations.CreateModel(
            name='PersonIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='lms.lmsperson')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(default='active', max_length=20)),
                ('type', models.CharField(default='semester', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'start_date'], name='lms_session_state_b89e58_idx')],
                'unique_together': {('name', 'start_date')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='lms.session'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('override_due_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.lmsperson')),
            ],
        ),
        migrations.AddIndex(
            model_name='lmsclass',
            index=models.Index(fields=['course', 'state'], name='lms_lmsclas_course__6936df_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsclass',
            index=models.Index(fields=['enrollment_count'], name='lms_lmsclas_enrollm_7a6ae7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lmsclass',
            unique_together={('course', 'name')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_section', 'due_date'], name='lms_assignm_class_s_aa0c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['state'], name='lms_assignm_state_a20722_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsperson',
            index=models.Index(fields=['email'], name='lms_lmspers_email_7abeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsperson',
            index=models.Index(fields=['roles'], name='lms_lmspers_roles_7c1282_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['role', 'state'], name='lms_enrollm_role_0e6296_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_section', 'role'], name='lms_enrollm_class_s_db50fb_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['final_numeric_grade'], name='lms_enrollm_final_n_9bae7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('person', 'class_section', 'role')},
        ),
        migrations.AddIndex(
            model_name='personidentifier',
            index=models.Index(fields=['type', 'value'], name='lms_personi_type_a85f29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personidentifier',
            unique_together={('person', 'type')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'session'], name='lms_course_departm_45885a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='lms_course_code_c2ddd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'department')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'submitted_at'], name='lms_submiss_student_17258d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['grade_points'], name='lms_submiss_grade_p_fed909_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
    ]
