# Generated by Django 5.2.7 on 2025-12-05 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='edlink_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='edlink_integration_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LmsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_id', models.UUIDField(db_index=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('type', models.CharField(max_length=20)),
                ('target', models.CharField(db_index=True, max_length=50)),
                ('target_id', models.UUIDField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customers.institution')),
            ],
            options={
                'db_table': 'lms_event',
                'indexes': [models.Index(fields=['integration_id', 'date'], name='lms_event_integra_494abc_idx'), models.Index(fields=['target', 'target_id'], name='lms_event_target_1f5469_idx'), models.Index(fields=['institution', 'date'], name='lms_event_institu_d65bed_idx')],
            },
        ),
    ]
