# Generated by Django 5.2.7 on 2025-12-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_institution_edlink_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='edlink_integration_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
