# Generated by Django 5.2.7 on 2026-03-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_institution_edlink_integration_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LmsEvent',
        ),
    ]
