# Generated by Django 5.2.7 on 2026-03-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_delete_lmsevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='edlink_access_token',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='edlink_integration_id',
        ),
    ]
