# Generated by Django 5.2.7 on 2025-12-02 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Google Frontend Application'", max_length=255)),
                ('target_role', models.CharField(blank=True, help_text="e.g., 'Software Engineer'", max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, help_text='Paste the full JD here for AI analysis.', null=True)),
                ('tailored_content', models.JSONField(blank=True, default=dict, help_text='The final structured data used to generate the PDF.')),
                ('ats_score', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, help_text='Suggestions to improve.', null=True)),
                ('template_style', models.CharField(choices=[('MODERN', 'Modern (Two Column)'), ('CLASSIC', 'Classic (ATS Friendly)'), ('CREATIVE', 'Creative')], default='CLASSIC', max_length=50)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='profiles.studentprofile')),
            ],
        ),
    ]
