# Generated by Django 5.2.7 on 2025-11-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='contact',
            field=models.CharField(default=9441637434, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='street',
            field=models.TextField(default='khammam'),
            preserve_default=False,
        ),
    ]
